#!/bin/sh
# Render one Modelfile per profile from profiles/<name>, system_prompt.txt,
# and examples.tsv. A profile can list its own example files, relative to the
# repo, on a "# examples: FILE..." line; otherwise it uses examples.tsv.
#
# Usage: ./gen-modelfiles.sh [OUTPUT_DIR]
#
# Writes Modelfile.<name> for every file in profiles/. The system prompt goes
# into a SYSTEM block and each line of the example files ("raw<TAB>edited") becomes
# a MESSAGE user / MESSAGE assistant pair (with \n in the edited column
# expanded to a line break), so the model sees the examples as
# real conversation turns. OUTPUT_DIR defaults to the repo directory, so
# running this with no arguments refreshes the committed Modelfiles. Run it
# after editing system_prompt.txt, examples.tsv, or anything in profiles/.

set -eu

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
OUT_DIR=${1:-$SCRIPT_DIR}
PROMPT="$SCRIPT_DIR/system_prompt.txt"

[ -f "$PROMPT" ]   || { printf 'error: %s not found\n' "$PROMPT" >&2; exit 1; }
[ -d "$OUT_DIR" ]  || mkdir -p "$OUT_DIR"

TAB=$(printf '\t')

for profile in "$SCRIPT_DIR"/profiles/*; do
    [ -f "$profile" ] || continue
    name=$(basename "$profile")
    out="$OUT_DIR/Modelfile.$name"
    files=$(awk '/^# examples:/ { sub(/^# examples:[[:space:]]*/, ""); print; exit }' "$profile")
    for f in ${files:-examples.tsv}; do
        [ -f "$SCRIPT_DIR/$f" ] || { printf 'error: %s not found (profiles/%s)\n' "$SCRIPT_DIR/$f" "$name" >&2; exit 1; }
    done
    {
        printf '# GENERATED by gen-modelfiles.sh from profiles/%s, system_prompt.txt, and %s.\n' "$name" "${files:-examples.tsv}"
        printf '# Do not edit this file; edit those and re-run ./gen-modelfiles.sh.\n\n'
        cat "$profile"
        printf '\nSYSTEM """\n'
        cat "$PROMPT"
        printf '"""\n\n'
        for f in ${files:-examples.tsv}; do
            while IFS="$TAB" read -r raw edited; do
                [ -n "$raw" ] || continue
                case "$raw" in '#'*) continue ;; esac
                printf 'MESSAGE user """%s"""\n' "$raw"
                printf 'MESSAGE assistant """%b"""\n' "$edited"
            done < "$SCRIPT_DIR/$f"
        done
    } > "$out"
    printf 'wrote %s\n' "$out"
done
